#include <iostream>
using namespace std;

int main(){

bool a = true; // The value of true is 1...
cout<< a<<endl; // It will print 1 because value of a is true...

bool b = false; // The value of false is 0...
cout<< b<<endl; // It will print 0 because the value of b is flase...

    return 0;
}

// Bool datatype is used to store true or false value in a variable...
// The value  of true is 1...
// The value of flase is 0...