#include <iostream>

using namespace std; // This is use to avoid typing std in cout<< and cin>>...

int main(){

cout<<"Enter space:"<<endl; // <<endl(endline):- Insert a new line and fluses... <<endl is a keyword...
                            // <<endl:- we can use this only when "using namespace" is included...

cout<<"Enter space\n"; // \n:- Insert a new line... \n is a charcter...
    return 0;
}