/*                    __________TEMPLATES_________

 # Template:- Independent Datatype is called Template...


 # There are mainly two types of Templates:-
   1. Template Class...
   2. Template Function...

1. Template Class:- It is also known as Genric Class...

2. Template Function:- It is also known as Genric Function...

*/