  /*                     OBJECT ORIENTED PROGRAMMING(OOPS)

1. Works on the concepts of classes and objects...

2. A class is a temlate to create objects...

3. Treats data as a critical(pricious) element...

4. Decomposes the problem in objects and builds data and function around the objects...
*/