   /*          ******************** WHY OOPS *******************

1. C++ language was designed with the main intention of adding object-oriented features to C language...

2. As the program size increases, readability, maintainbility and bug-free nature of program decreases...

3. This way the major problem with language like C which relied upon functions or procedures
                                          (Hence the name is procedural programming language)...

4. As a result, the possibility of not addressing the problem in an effective manner was high...

5. Also, as data was almost neglected, data security was easily compromised...

6. Using classes solves this problem by modelling program as a real world scenario...

*/