/*                     BASIC CONCEPTS IN OBJECT ORIENTED PROGRAMMING

1. CLASSES:- Basic template for creating objects...

2. OBJECTS:- Basic run time entities...

3. DATA ABSTRACTION & ENCAPSULATION:- Wrappping data and functions into single unit...

4. INHERITANCE:- Properties of one class can be inherited into others...

5. POLYMORPHISM:- Ability to take more than one forms...

6. DYNAMIC BINDING:- Code which will execute is not known until the program...

7. MESSAGE PASSING:- Object.message(Information) call format...

*/