/*                        BENEFITS OF OBJECT ORIENTED PROGRMMING

1. Better code reusablity using objects and Inheritance...

2. Principle of data hiding helps build secure systems...

3. Multiple objects can co-exist without any interferene...

4. Software complexity can be easily managed...


*/