   //  OOPs - Classes and objects...
   
   // C++ --> initially called --> C with classes by stroustroup...
   // Class --> extension of structure(in C)...

   // Structures had limitations:-
   //           - members are public...
   //           - No methods...

   // Classes --> Structure + more...
   // Classes --> Can have methods and properties...
   // Classes --> Can make few members as private & few as public...
   // Structures in C++ are typedefed already(not need to typedef)...

   // You can declare Objects along with the class declaration like this:-
       /*    class Employee{
           // Class defination
       } Rohit, Mohit , Lohit; */

       // Rohit.salary = 8 // We can't access data members outside the class...