// Friend function:- It is a function which is not the member of class,
//                   still it can access the private and protected member of class...

// Friend function can become friend of more than one class...


/*
                Properties of friend funtion
1. Not in the scope of class...
2. It can't be called with the object...
3. Can be invoked without the object...
4. Usually contains objects as arguments...
5. Can be declared anywhere in class(private or public)...

6. It cannot access the members directly, It needs objects...
*/