/*                      __________POLYMORPHISM__________

Polymorphism(Poly means Multi, Morphism means Names):- 
- One name multiple forms...
- eg function overloading , operator overloading...

Polymorphism:- It means same object having different behaviour...   

# Types of Polymorphism:

1. Compiletime Polymorphism...
2. Runtime Polymorphism...

Compiletime:- The time duration in which programming code is converted to machine code...
              OR:- When the programmer is writing the program...

Runtime:- Runtime is when the code is executed(running)...

1. Compiletime Polymorphism:
   1.1 - Function Overloading...
   1.2 - Operator Overloading...

2. Runtime Polymorphism:
   2.1 - Virtual Functions...
*/